create table users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table transports (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    transport_type VARCHAR(30) NOT NULL,
    vin VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table delivery_men (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    own_id VARCHAR(30) NOT NULL,
    name VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    transport_id INT UNSIGNED, FOREIGN KEY (transport_id) REFERENCES transports(id)
);

create table products (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    vin VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table deliveries (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    delivery_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delivery_man_id INT UNSIGNED, FOREIGN KEY (delivery_man_id) REFERENCES delivery_men(id),
    product_id INT UNSIGNED, FOREIGN KEY (product_id) REFERENCES products(id)
);
